spring.application.name=backends
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/lms
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=Hira2006@
=======
spring.datasource.password=hzkk4567@A
>>>>>>> 037d5826f8d948d73cb0531952aaf834a78ec1c8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true